version: "3"
services:
  api:
    build: ./surprise-app/backend
    ports:
      - "9080:9080"
    depends_on:
      - db
    container_name: surprise-app-api

  client:
    build: ./surprise-app/frontend
    ports:
      - "3000:3000"
    container_name: surprise-app-client

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: surprise-app-db
