version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: surprise-db
  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: surprise-api
  client:
    build: ./frontend
    ports:
      - "80:80"
    container_name: surprise-client
