version: "3"
services:
  api:
    build: ./backend
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_URI_TEST: ${MONGODB_URI_TEST}
    ports:
      - "9080:9080"
    depends_on:
      - mongodb
    container_name: surprise-app-api

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: surprise-app-client

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: surprise-app-db
